name: Build thallheim.com

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  CLICOLOR: 1
  
jobs:
  site-build:
    name: Build thallheim.com
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        rust: ["stable"]
    continue-on-error: ${{ matrix.rust != 'stable' }}
    runs-on: self-hosted
#    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Rustify
        uses: dtolnay/rust-toolchain@stable
      - name: Install Cobalt  
        run: |
          echo "[INFO] Ensure Cobalt present:"
          cargo install cobalt-bin || echo "[INFO] Cobalt installed: YES"
      - name: Build site
        run: |
          cobalt build
