name: Build site

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:

  do-test-build:
    name: Site test build
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        rust: ["stable"]
    continue-on-error: ${{ matrix.rust != 'stable' }}
#    runs-on: ${{ matrix.os }}
    runs-on: self-hosted

    steps:
      - name: Init Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cobalt
        run: |
          cargo install cobalt-bin || echo "[INFO] Cobalt installed: YES"
      - name: Repo checkout
        uses: actions/checkout@v4
      - name: "[DEBUG] Show CWP"
        run: |
          pwd
      - name: "[DEBUG] Show Cobalt dest path"
        run: |
          cobalt debug config | grep destination
      - name: Build site
        run: |
          cobalt build
      - name: Upload test build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: site-artifacts
          path: staged-test-build
      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Create and/or switch to test branch
        run: |
          git checkout test-build || git checkout -b test-build
      - name: Clean test branch
        run: |
          git rm -r .
      - name: Commit and push build to test branch
        run: |
          git add .
          git commit -m "Deploy build to test branch"
          git push origin test-build

