name: Build thallheim.com

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  CLICOLOR: 1
  
jobs:
  site-build:
    name: Site-build
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        rust: ["stable"]
    continue-on-error: ${{ matrix.rust != 'stable' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build site
        run: |
          cobalt build
