name: Deploy production build

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:

  do-production-build:
    permissions:
      actions: write
      contents: write
      deployments: write
      id-token: write
      issues: none
      packages: write
      pages: none
      pull-requests: none
      repository-projects: none
      security-events: read
      statuses: write

    name: Deploy test build to production
    strategy:
      fail-fast: false
    runs-on: self-hosted
    steps:
      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Switch to production branch
        uses: actions/checkout@v4
        with:
          ref: production-build
      - name: Fast-forward or merge production build
        run: |
          git pull --ff-only || git merge --no-ff
      - name: Show status and push
        run: |
          git status
          git push
