name: Deploy production build

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

permissions: write-all

jobs:

  do-production-build:
    # actions: write
    # contents: write
    # deployments: write
    # id-token: write
    # issues: none
    # packages: write
    # pages: none
    # pull-requests: none
    # repository-projects: none
    # security-events: read
    # statuses: write

    name: Deploy test build to production
    strategy:
      fail-fast: false
    runs-on: self-hosted

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: "Checkout: test branch"
        uses: actions/checkout@v4
        with:
          ref: test-build
      - name: "Checkout: production branch"
        uses: actions/checkout@v4
        with:
          ref: production-build
      - name: Merge test build into production branch
        run: |
          git merge --no-ff origin/test-build
          git push origin production-build
