name: Deploy production build

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

permissions: write-all

jobs:

  do-production-build:
      # actions: write
      # contents: write
      # deployments: write
      # id-token: write
      # issues: none
      # packages: write
      # pages: none
      # pull-requests: none
      # repository-projects: none
      # security-events: read
      # statuses: write

    name: Deploy test build to production
    strategy:
      fail-fast: false
    runs-on: self-hosted

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Switch to production branch
        uses: actions/checkout@v3
        with:
          ref: production-build
      - name: Push test build to production branch
        run: |
          git clone --branch test-build --single-branch https://github.com/thallheim/thallheim.com.git .
          git add .
          git commit -m "Deploy test build to production"
          git push origin production-build
