name: Deploy production build

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

permissions: write-all

jobs:

  do-production-build:
    # actions: write
    # contents: write
    # deployments: write
    # id-token: write
    # issues: none
    # packages: write
    # pages: none
    # pull-requests: none
    # repository-projects: none
    # security-events: read
    # statuses: write

    name: Deploy test build to production
    strategy:
      fail-fast: false
    runs-on: self-hosted
    steps:
      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
#          clean: true
      # - name: Check for changes
      #   id: git-check
      #   run: |
      #     if [[ -n $(git status --porcelain) ]]; then
      #       echo "Changes detected."
      #     else
      #       echo "No changes to commit. Exiting."
      #       exit 0
      #     fi
      # - name: Commit and push changes
      #   if: steps.git-check.outputs.run == 'Changes detected.'
      #   run: |
      #     git add .
      #     git commit -am "Deploy test build to production branch"
      #     git push origin production-build
      - name: Switch to production branch
        run: |
          git switch production-build
      - name: Merge (FF) test build into production branch
        run: |
          git merge --ff-only test-build
          git push
